// Spike E1, question 1: quotes the declarations the hand-off depends on,
// verbatim with their doc comments, from the types the engine laid beside the
// plugin when it loaded it (`claude --plugin-dir spikes/e1-handoff`).
// Usage (from the repo root): node spikes/e1-handoff/extract-types.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const FILE = 'spikes/e1-handoff/.claude-plugin/types/claude-code/index.d.ts';
const OUT = 'spikes/e1-handoff/results/types.md';
const lines = readFileSync(FILE, 'utf8').split('\n');

const TARGETS = [
  ['$.command.list', /^ {10}list: \(\) => Promise<CommandInfo\[\]>;/],
  ['$.command.run', /^ {10}run: EventCalls\['command'\]\['run'\];/],
  ['$.command.register', /^ {10}register: \(command: CommandSpec\)/],
  ['EventCalls.command', /^ {6}command: \{$/, 'EventCalls'],
  ['CommandRunArgs', /^ {2}export type CommandRunArgs = /],
  ['CommandRunInput', /^ {2}export type CommandRunInput = /],
  ['CommandRunResult', /^ {2}export type CommandRunResult = /],
  ['CommandSpec', /^ {2}export type CommandSpec = /],
  ['CommandInfo', /^ {2}export type CommandInfo = /],
  ['$.prompt.submit', /^ {10}submit: EventCalls\['prompt'\]\['submit'\];/],
  ['$.prompt.fill', /^ {10}fill: \(input: PromptFillArgs\) => Promise<PromptFilled>;/],
  ['PromptSubmitArgs', /^ {2}export type PromptSubmitArgs = /],
  ['PromptSubmitResult', /^ {2}export type PromptSubmitResult = /],
  ['PromptFillArgs', /^ {2}export type PromptFillArgs = /],
  ['PromptFilled', /^ {2}export type PromptFilled = /],
  ['ButtonProps (onPress, hotkey)', /^ {2}export type ButtonProps = /],
  ["Events 'ui.press'", /^ {6}'ui\.press': UiPressArgument;/],
  ['UiPressArgument', /^ {2}export type UiPressArgument = /],
  ['UiPressResult', /^ {2}export type UiPressResult = /],
];

function docStart(i) {
  let s = i;
  if (lines[s - 1]?.trim() === '*/') {
    s -= 1;
    while (s > 0 && !lines[s].trim().startsWith('/**')) s -= 1;
  }
  return s;
}

function blockEnd(i) {
  let depth = 0;
  for (let j = i; j < lines.length; j += 1) {
    const code = lines[j].replace(/\/\/.*$/, '');
    if (/^\s*(\/\*\*|\*)/.test(lines[j])) continue;
    for (const ch of code) {
      if (ch === '{' || ch === '(') depth += 1;
      if (ch === '}' || ch === ')') depth -= 1;
    }
    if (depth <= 0 && /[;,]\s*$|^\s*\};?\s*$/.test(code)) return j;
  }
  return i;
}

const out = [
  '# E1: declarations the hand-off depends on',
  '',
  `Quoted verbatim from \`${FILE}\`, which the engine wrote when it loaded the plugin (first line: \`${lines[0]}\`). Generated by \`node spikes/e1-handoff/extract-types.mjs\`; line numbers refer to that file.`,
  '',
];
for (const [name, re, after] of TARGETS) {
  let from = 0;
  if (after) from = lines.findIndex(l => l.includes(`export type ${after} = {`));
  const i = lines.findIndex((l, k) => k >= from && re.test(l));
  if (i < 0) {
    out.push(`## ${name}`, '', '_Not found in this build._', '');
    continue;
  }
  const s = docStart(i);
  const e = blockEnd(i);
  out.push(`## ${name}`, '', `Lines ${s + 1}–${e + 1}:`, '', '```ts', ...lines.slice(s, e + 1), '```', '');
}
writeFileSync(OUT, out.join('\n'));
console.log(`wrote ${OUT}`);
